[package]
name = "opal"
version = "0.0.0"
authors = ["marc1 <m@marc.rs>"]
edition = "2018"
license = "MIT"

[[bin]]
name = "opal"
path = "crates/bin/opal.rs"

[workspace]
members = ["crates/viewport"]

[dependencies]
viewport = { path = "crates/viewport" }

