[package]
name = "opal"
version = "0.1.0"
authors = ["marc1 <m@marc.rs>"]
edition = "2018"
license = "MIT"

[[bin]]
name = "opal"
path = "crates/bin/opal.rs"

[workspace]
members = [
    "crates/lib",
    "crates/tui",
]

[dependencies]
opal-lib = { version = "0.1.0", path = "crates/lib" }
